/*
 *     Copyright 2025 The Dragonfly Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by mockery. DO NOT EDIT.

package storage

import (
	context "context"

	metadata "d7y.io/snapshotter/internal/metadata"
	mock "github.com/stretchr/testify/mock"

	os "os"

	storage "d7y.io/snapshotter/internal/storage"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// Export provides a mock function with given fields: ctx, outputDir, file, srcFilename
func (_m *Storage) Export(ctx context.Context, outputDir string, file metadata.File, srcFilename string) error {
	ret := _m.Called(ctx, outputDir, file, srcFilename)

	if len(ret) == 0 {
		panic("no return value specified for Export")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metadata.File, string) error); ok {
		r0 = rf(ctx, outputDir, file, srcFilename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_Export_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Export'
type Storage_Export_Call struct {
	*mock.Call
}

// Export is a helper method to define mock.On call
//   - ctx context.Context
//   - outputDir string
//   - file metadata.File
//   - srcFilename string
func (_e *Storage_Expecter) Export(ctx interface{}, outputDir interface{}, file interface{}, srcFilename interface{}) *Storage_Export_Call {
	return &Storage_Export_Call{Call: _e.mock.On("Export", ctx, outputDir, file, srcFilename)}
}

func (_c *Storage_Export_Call) Run(run func(ctx context.Context, outputDir string, file metadata.File, srcFilename string)) *Storage_Export_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metadata.File), args[3].(string))
	})
	return _c
}

func (_c *Storage_Export_Call) Return(_a0 error) *Storage_Export_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_Export_Call) RunAndReturn(run func(context.Context, string, metadata.File, string) error) *Storage_Export_Call {
	_c.Call.Return(run)
	return _c
}

// GetContentPath provides a mock function with given fields: ctx, filename
func (_m *Storage) GetContentPath(ctx context.Context, filename string) string {
	ret := _m.Called(ctx, filename)

	if len(ret) == 0 {
		panic("no return value specified for GetContentPath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, filename)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Storage_GetContentPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContentPath'
type Storage_GetContentPath_Call struct {
	*mock.Call
}

// GetContentPath is a helper method to define mock.On call
//   - ctx context.Context
//   - filename string
func (_e *Storage_Expecter) GetContentPath(ctx interface{}, filename interface{}) *Storage_GetContentPath_Call {
	return &Storage_GetContentPath_Call{Call: _e.mock.On("GetContentPath", ctx, filename)}
}

func (_c *Storage_GetContentPath_Call) Run(run func(ctx context.Context, filename string)) *Storage_GetContentPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_GetContentPath_Call) Return(_a0 string) *Storage_GetContentPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_GetContentPath_Call) RunAndReturn(run func(context.Context, string) string) *Storage_GetContentPath_Call {
	_c.Call.Return(run)
	return _c
}

// HardlinkSnapshot provides a mock function with given fields: ctx, baseDir, srcfile, destFilename
func (_m *Storage) HardlinkSnapshot(ctx context.Context, baseDir string, srcfile storage.File, destFilename string) error {
	ret := _m.Called(ctx, baseDir, srcfile, destFilename)

	if len(ret) == 0 {
		panic("no return value specified for HardlinkSnapshot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, storage.File, string) error); ok {
		r0 = rf(ctx, baseDir, srcfile, destFilename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_HardlinkSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HardlinkSnapshot'
type Storage_HardlinkSnapshot_Call struct {
	*mock.Call
}

// HardlinkSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - baseDir string
//   - srcfile storage.File
//   - destFilename string
func (_e *Storage_Expecter) HardlinkSnapshot(ctx interface{}, baseDir interface{}, srcfile interface{}, destFilename interface{}) *Storage_HardlinkSnapshot_Call {
	return &Storage_HardlinkSnapshot_Call{Call: _e.mock.On("HardlinkSnapshot", ctx, baseDir, srcfile, destFilename)}
}

func (_c *Storage_HardlinkSnapshot_Call) Run(run func(ctx context.Context, baseDir string, srcfile storage.File, destFilename string)) *Storage_HardlinkSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(storage.File), args[3].(string))
	})
	return _c
}

func (_c *Storage_HardlinkSnapshot_Call) Return(_a0 error) *Storage_HardlinkSnapshot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_HardlinkSnapshot_Call) RunAndReturn(run func(context.Context, string, storage.File, string) error) *Storage_HardlinkSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// Prune provides a mock function with given fields: ctx, filename
func (_m *Storage) Prune(ctx context.Context, filename string) error {
	ret := _m.Called(ctx, filename)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, filename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_Prune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prune'
type Storage_Prune_Call struct {
	*mock.Call
}

// Prune is a helper method to define mock.On call
//   - ctx context.Context
//   - filename string
func (_e *Storage_Expecter) Prune(ctx interface{}, filename interface{}) *Storage_Prune_Call {
	return &Storage_Prune_Call{Call: _e.mock.On("Prune", ctx, filename)}
}

func (_c *Storage_Prune_Call) Run(run func(ctx context.Context, filename string)) *Storage_Prune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_Prune_Call) Return(_a0 error) *Storage_Prune_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_Prune_Call) RunAndReturn(run func(context.Context, string) error) *Storage_Prune_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreSnapshotFromContent provides a mock function with given fields: ctx, filename
func (_m *Storage) RestoreSnapshotFromContent(ctx context.Context, filename string) error {
	ret := _m.Called(ctx, filename)

	if len(ret) == 0 {
		panic("no return value specified for RestoreSnapshotFromContent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, filename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_RestoreSnapshotFromContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreSnapshotFromContent'
type Storage_RestoreSnapshotFromContent_Call struct {
	*mock.Call
}

// RestoreSnapshotFromContent is a helper method to define mock.On call
//   - ctx context.Context
//   - filename string
func (_e *Storage_Expecter) RestoreSnapshotFromContent(ctx interface{}, filename interface{}) *Storage_RestoreSnapshotFromContent_Call {
	return &Storage_RestoreSnapshotFromContent_Call{Call: _e.mock.On("RestoreSnapshotFromContent", ctx, filename)}
}

func (_c *Storage_RestoreSnapshotFromContent_Call) Run(run func(ctx context.Context, filename string)) *Storage_RestoreSnapshotFromContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_RestoreSnapshotFromContent_Call) Return(_a0 error) *Storage_RestoreSnapshotFromContent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_RestoreSnapshotFromContent_Call) RunAndReturn(run func(context.Context, string) error) *Storage_RestoreSnapshotFromContent_Call {
	_c.Call.Return(run)
	return _c
}

// StatContent provides a mock function with given fields: ctx, baseDir, file
func (_m *Storage) StatContent(ctx context.Context, baseDir string, file storage.File) (os.FileInfo, error) {
	ret := _m.Called(ctx, baseDir, file)

	if len(ret) == 0 {
		panic("no return value specified for StatContent")
	}

	var r0 os.FileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, storage.File) (os.FileInfo, error)); ok {
		return rf(ctx, baseDir, file)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, storage.File) os.FileInfo); ok {
		r0 = rf(ctx, baseDir, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, storage.File) error); ok {
		r1 = rf(ctx, baseDir, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_StatContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatContent'
type Storage_StatContent_Call struct {
	*mock.Call
}

// StatContent is a helper method to define mock.On call
//   - ctx context.Context
//   - baseDir string
//   - file storage.File
func (_e *Storage_Expecter) StatContent(ctx interface{}, baseDir interface{}, file interface{}) *Storage_StatContent_Call {
	return &Storage_StatContent_Call{Call: _e.mock.On("StatContent", ctx, baseDir, file)}
}

func (_c *Storage_StatContent_Call) Run(run func(ctx context.Context, baseDir string, file storage.File)) *Storage_StatContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(storage.File))
	})
	return _c
}

func (_c *Storage_StatContent_Call) Return(_a0 os.FileInfo, _a1 error) *Storage_StatContent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_StatContent_Call) RunAndReturn(run func(context.Context, string, storage.File) (os.FileInfo, error)) *Storage_StatContent_Call {
	_c.Call.Return(run)
	return _c
}

// StatSnapshot provides a mock function with given fields: ctx, filename
func (_m *Storage) StatSnapshot(ctx context.Context, filename string) (os.FileInfo, error) {
	ret := _m.Called(ctx, filename)

	if len(ret) == 0 {
		panic("no return value specified for StatSnapshot")
	}

	var r0 os.FileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (os.FileInfo, error)); ok {
		return rf(ctx, filename)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) os.FileInfo); ok {
		r0 = rf(ctx, filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_StatSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatSnapshot'
type Storage_StatSnapshot_Call struct {
	*mock.Call
}

// StatSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - filename string
func (_e *Storage_Expecter) StatSnapshot(ctx interface{}, filename interface{}) *Storage_StatSnapshot_Call {
	return &Storage_StatSnapshot_Call{Call: _e.mock.On("StatSnapshot", ctx, filename)}
}

func (_c *Storage_StatSnapshot_Call) Run(run func(ctx context.Context, filename string)) *Storage_StatSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_StatSnapshot_Call) Return(_a0 os.FileInfo, _a1 error) *Storage_StatSnapshot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_StatSnapshot_Call) RunAndReturn(run func(context.Context, string) (os.FileInfo, error)) *Storage_StatSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// WriteContent provides a mock function with given fields: ctx, baseDir, file
func (_m *Storage) WriteContent(ctx context.Context, baseDir string, file storage.File) (os.FileInfo, error) {
	ret := _m.Called(ctx, baseDir, file)

	if len(ret) == 0 {
		panic("no return value specified for WriteContent")
	}

	var r0 os.FileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, storage.File) (os.FileInfo, error)); ok {
		return rf(ctx, baseDir, file)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, storage.File) os.FileInfo); ok {
		r0 = rf(ctx, baseDir, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, storage.File) error); ok {
		r1 = rf(ctx, baseDir, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_WriteContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteContent'
type Storage_WriteContent_Call struct {
	*mock.Call
}

// WriteContent is a helper method to define mock.On call
//   - ctx context.Context
//   - baseDir string
//   - file storage.File
func (_e *Storage_Expecter) WriteContent(ctx interface{}, baseDir interface{}, file interface{}) *Storage_WriteContent_Call {
	return &Storage_WriteContent_Call{Call: _e.mock.On("WriteContent", ctx, baseDir, file)}
}

func (_c *Storage_WriteContent_Call) Run(run func(ctx context.Context, baseDir string, file storage.File)) *Storage_WriteContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(storage.File))
	})
	return _c
}

func (_c *Storage_WriteContent_Call) Return(_a0 os.FileInfo, _a1 error) *Storage_WriteContent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_WriteContent_Call) RunAndReturn(run func(context.Context, string, storage.File) (os.FileInfo, error)) *Storage_WriteContent_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
