/*
 *     Copyright 2025 The Dragonfly Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by mockery. DO NOT EDIT.

package dragonfly

import (
	context "context"

	dragonfly "d7y.io/snapshotter/pkg/dragonfly"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Download provides a mock function with given fields: ctx, req
func (_m *Client) Download(ctx context.Context, req *dragonfly.DownloadRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dragonfly.DownloadRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type Client_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dragonfly.DownloadRequest
func (_e *Client_Expecter) Download(ctx interface{}, req interface{}) *Client_Download_Call {
	return &Client_Download_Call{Call: _e.mock.On("Download", ctx, req)}
}

func (_c *Client_Download_Call) Run(run func(ctx context.Context, req *dragonfly.DownloadRequest)) *Client_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dragonfly.DownloadRequest))
	})
	return _c
}

func (_c *Client_Download_Call) Return(_a0 error) *Client_Download_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_Download_Call) RunAndReturn(run func(context.Context, *dragonfly.DownloadRequest) error) *Client_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, req
func (_m *Client) Upload(ctx context.Context, req *dragonfly.UploadRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dragonfly.UploadRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type Client_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dragonfly.UploadRequest
func (_e *Client_Expecter) Upload(ctx interface{}, req interface{}) *Client_Upload_Call {
	return &Client_Upload_Call{Call: _e.mock.On("Upload", ctx, req)}
}

func (_c *Client_Upload_Call) Run(run func(ctx context.Context, req *dragonfly.UploadRequest)) *Client_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dragonfly.UploadRequest))
	})
	return _c
}

func (_c *Client_Upload_Call) Return(_a0 error) *Client_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_Upload_Call) RunAndReturn(run func(context.Context, *dragonfly.UploadRequest) error) *Client_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
